name: Test

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]

jobs:
  test-packaging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: "Run pip install"
        run: |
          pip install .


  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run poetry install
        run: |
          poetry env use '3.10'
          poetry install
          poetry self add "poetry-dynamic_versioning[plugin]"

      - name: Run pytest
        run: |
          poetry run pytest
